project:
  type: website

website:
  open-graph: true
  favicon: /assets/img/favicon/favicon-32x32.png
  repo-url: https://github.com/filipemtz/filipemtz.github.io
  site-url: "https://filipemtz.github.io/"
  repo-actions: [issue]
  title: "Filipe Mutz"
  reader-mode: true
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - pages/publications.qmd
      #- pages/projects.qmd
      - pages/teaching.qmd
      - pages/supervision.qmd
      #- pages/posts.qmd

format:
  html:
    date-format: "yyyy/MM/dd"
    theme: cerulean
    css: css/styles.css
    toc: true
    anchor-sections: true
    link-external-newwindow: true

